import 'bootstrap/dist/css/bootstrap.min.css';
import './styles/globals.module.scss';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { AuthProvider } from './context/AuthProvider';
import Header from './components/header';
import Footer from './components/footer';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: process.env.APP_NAME,
	description: 'Generated by create next app',
}

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {	
	return (
		<html lang="pt-br">
			<body className={inter.className}>
				<AuthProvider>
					<Header />
					<main className='container py-3'>{children}</main>
					<Footer />
				</AuthProvider>
			</body>
		</html>
	);
}
